/**
 * `/team` final-message assembly.
 *
 * The closing contract and the per-proposal adoption status are generated by
 * code from structured tracking; the synthesis sub-call never authors them.
 * When its text disagrees with the tracking, the tracking wins — an invalid
 * recommendation is dropped here with an explicit note.
 */
import type { TeamAlignmentOutput, TeamProposalRecord, TeamSynthesisOutput } from "./types";

/** Fixed closing contract, verbatim from docs-zh-CN/requirements/team.md §2.7. */
export const TEAM_CLOSING_CONTRACT = [
	'> 选择方案请直接回复（如"选择方案 A"）。选择仅确认该方案、其验收标准与执行前检查，不触发实施；如需修改代码，请另行明确要求。若存在影响选择的"需求理解差异"，请先回答该差异并带答案重跑 `/team`，不要在不同前提的方案间盲选。',
].join("\n");

export interface AssembleReportArgs {
	alignment: TeamAlignmentOutput;
	synthesis: TeamSynthesisOutput;
	proposals: readonly TeamProposalRecord[];
	/** Notes about incomplete participation, wiki gaps, etc. */
	participationNotes: readonly string[];
}

export interface AssembleReportResult {
	ok: true;
	markdown: string;
	/** True when structured tracking overrode the synthesis recommendation. */
	droppedRecommendation: boolean;
}

export interface AssembleReportConflict {
	ok: false;
	error: string;
}

function proposalLabel(record: TeamProposalRecord): string {
	return `方案 ${record.label}`;
}

function statusLine(record: TeamProposalRecord): string {
	if (record.excludedFromOptions) {
		return `⛔ 尚不可采用 — ${record.exclusionReason ?? "不可作为最终选项"}`;
	}
	if (record.unresolvedBlocking.length > 0) {
		const cap = record.blockedAfterRoundCap ? "（两轮修订后仍未解决）" : "";
		return `⛔ 尚不可采用 — 未解决阻断问题${cap}：${record.unresolvedBlocking.join("；")}`;
	}
	if (record.blockedAfterRoundCap) {
		return "⛔ 尚不可采用 — 两轮修订后仍有阻断问题";
	}
	return "✅ 可作为选项";
}

/** §2.8 adoptability: offered as a final option, with no unresolved blocking finding and no round-cap block. */
function isAdoptable(record: TeamProposalRecord): boolean {
	return !record.excludedFromOptions && record.unresolvedBlocking.length === 0 && !record.blockedAfterRoundCap;
}

/** Whether the recommendation may stand: an existing, non-excluded, non-blocked proposal. */
function recommendationIsValid(synthesis: TeamSynthesisOutput, proposals: readonly TeamProposalRecord[]): boolean {
	const label = synthesis.recommendedProposal.trim();
	if (!label) return false;
	const record = proposals.find(candidate => candidate.label === label);
	if (!record) return false;
	return isAdoptable(record);
}

/**
 * Conditional adoption clauses (§2.7 未采纳方向): explaining *when* a blocked
 * proposal could become adoptable — "在阻断问题 b 解决后即可采用" — is expected
 * synthesis content, not a tracking override. A clause is stripped only when
 * its adoption verb is explicitly guarded: either a conditional connective
 * leads into it, or a resolution verb is followed by an explicit posteriority
 * marker (后/之后/之时). The posteriority requirement keeps "…解决方案 A 可采用"
 * (解决方案 reads as "adopt solution A", not resolution + 后) unstripped, so an
 * unconditional recommendation still conflicts.
 */
const CONDITIONAL_ADOPTION_CLAUSE = new RegExp(
	[
		"(?:一旦|如果|若|只要|待|假如|倘若)[^。\\n]{0,20}?(?:解决|修复|解除|满足|关闭|消除|证实|确认)[^。\\n]{0,8}?(?:之后|以后|之时|后)?[^。\\n]{0,4}?(?:即|便|才|再|就)?(?:可|可以)?(?:采用|推荐|首选)",
		"(?:解决|修复|解除|满足|关闭|消除|证实|确认)[^。\\n]{0,8}?(?:之后|以后|之时|后)(?:即|便|才|再|就|方)?(?:可|可以)?(?:采用|推荐|首选)",
	].join("|"),
	"gu",
);

/** A model-authored adoption claim must not override the tracked proposal status. */
function synthesisBodyConflict(
	synthesis: TeamSynthesisOutput,
	proposals: readonly TeamProposalRecord[],
): string | undefined {
	const body = synthesis.reportMarkdown;
	if (body.includes("【推荐】")) return "综合正文自行写入了【推荐】标记";
	const statements = body.split(/(?:[。！？；;.!?，,、\r\n]|但是|但|而|却)/u);
	for (const record of proposals) {
		if (isAdoptable(record)) continue;
		const label = `方案${record.label}`;
		for (const statement of statements) {
			const compact = statement.replace(/\s+/gu, "");
			const positiveClaims = compact
				.replace(CONDITIONAL_ADOPTION_CLAUSE, "")
				.replace(/(?:不(?:可采用|可以采用|推荐|建议采用)|并非首选|不是首选)/gu, "");
			if (
				(compact.includes(label) || compact.includes(`${record.label}方案`)) &&
				/(?:可采用|可以采用|推荐|首选)/u.test(positiveClaims)
			) {
				return `综合正文建议采用已标记为“尚不可采用”的方案 ${record.label}`;
			}
		}
	}
	return undefined;
}

export function assembleTeamReport(args: AssembleReportArgs): AssembleReportResult | AssembleReportConflict {
	const { alignment, synthesis, proposals } = args;
	const conflict = synthesisBodyConflict(synthesis, proposals);
	if (conflict) return { ok: false, error: conflict };
	const sections: string[] = [];

	const choiceAffecting = alignment.interpretationDifferences.filter(difference => difference.affectsChoice);
	if (choiceAffecting.length > 0) {
		const lines = choiceAffecting.map(
			difference => `> - ${difference.ambiguity}：${difference.interpretations.map(view => view.view).join(" / ")}`,
		);
		sections.push(
			[
				"> ⚠️ **存在实质影响方案选择的需求理解差异——请先回答差异、带答案重跑 `/team`，不要在不同前提的方案间盲选：**",
				...lines,
			].join("\n"),
		);
	}

	sections.push(synthesis.reportMarkdown.trim());

	const statusRows = proposals.map(
		record =>
			`| ${proposalLabel(record)} | ${statusLine(record)} | 提案${record.participant.isSessionModel ? "（会话模型）" : ""}；审查轮数 ${record.reviews.length}；修订轮数 ${record.roundsUsed} |`,
	);
	sections.push(
		[
			"### 方案状态（结构化追踪，机械生效）",
			"",
			"| 方案 | 状态 | 参与情况 |",
			"| --- | --- | --- |",
			...statusRows,
			"",
		].join("\n"),
	);

	if (args.participationNotes.length > 0) {
		sections.push(["### 参与完整性与证据缺口", "", ...args.participationNotes.map(note => `- ${note}`)].join("\n"));
	}

	let droppedRecommendation = false;
	if (recommendationIsValid(synthesis, proposals)) {
		const preconditions = synthesis.recommendationPreconditions
			? `（前提：${synthesis.recommendationPreconditions}）`
			: "";
		sections.push(
			`**【推荐】${proposalLabel(proposals.find(p => p.label === synthesis.recommendedProposal)!)}** — ${synthesis.recommendationReason}${preconditions}`,
		);
	} else if (synthesis.recommendedProposal.trim()) {
		droppedRecommendation = true;
		sections.push(
			`> 结构化追踪否决了综合子调用对“${synthesis.recommendedProposal}”的推荐：该方案不存在、不可作为最终选项或仍有未解决阻断问题，故不给出推荐标记。`,
		);
	}

	sections.push(TEAM_CLOSING_CONTRACT);

	return {
		ok: true,
		markdown: [`## /team 多模型讨论结果（team-result）`, "", sections.join("\n\n")].join("\n"),
		droppedRecommendation,
	};
}

/** Failure message for runs that must not produce a half-finished conclusion. */
export function assembleTeamFailure(question: string, reason: string): string {
	return [
		"## /team 多模型讨论未完成（team-incomplete）",
		"",
		`本次流程未完成：${reason}`,
		"",
		"依据约定不输出半成品结论；请处理上述问题后重新发起 `/team`。",
		"",
		`> 原始问题：${question.slice(0, 500)}`,
	].join("\n");
}
